version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=timestamp
      - POSTGRES_USER=husamorbi
      - POSTGRES_PASSWORD=password
    networks:
      - pfemicroservice
    ports:
      - 5434:5432
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/timestamp
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - pfemicroservice
  adminer:
    image: adminer
    ports:
      - 8089:8080
    restart: unless-stopped
networks:
  pfemicroservice:
    driver: bridge
